# Generated by Django 2.0.6 on 2018-06-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean', models.CharField(default='설명 없음', max_length=200)),
                ('english', models.CharField(default='No description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean', models.CharField(default='이름 없음', max_length=12)),
                ('english', models.CharField(default='No name', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name'),
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name'),
        ),
    ]
