# Generated by Django 2.0.6 on 2018-06-30 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20180701_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name'),
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name'),
        ),
    ]
