# Generated by Django 2.0.6 on 2018-06-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20180701_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemontype',
            name='ineffective_typs',
            field=models.ManyToManyField(blank=True, related_name='_pokemontype_ineffective_typs_+', to='pokedex.PokemonType'),
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='not_very_effective_types',
            field=models.ManyToManyField(blank=True, related_name='_pokemontype_not_very_effective_types_+', to='pokedex.PokemonType'),
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='super_effective_types',
            field=models.ManyToManyField(blank=True, related_name='_pokemontype_super_effective_types_+', to='pokedex.PokemonType'),
        ),
    ]
