# Generated by Django 2.0.6 on 2018-06-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20180701_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
