# Generated by Django 2.0.6 on 2018-06-30 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_pokemonability'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonability',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name'),
        ),
    ]
