# Generated by Django 2.0.6 on 2018-07-01 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_pokemonability_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('damage', models.IntegerField(default=60)),
                ('accuracy', models.FloatField(default=1.0)),
                ('pp', models.IntegerField(default=5)),
                ('max_pp', models.IntegerField(default=10)),
                ('priority', models.IntegerField(default=0)),
                ('is_contact', models.BooleanField(default=False)),
                ('affected_by_magic_coat', models.BooleanField(default=True)),
                ('affected_by_bright_powder', models.BooleanField(default=True)),
                ('affected_by_protect', models.BooleanField(default=True)),
                ('affected_by_snatch', models.BooleanField(default=True)),
                ('affected_by_kings_rock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonMoveCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=1.0)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Description')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_attack',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_defense',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_special_attack',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_special_defense',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_speed',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='index_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(blank=True, to='pokedex.PokemonType'),
        ),
        migrations.AddField(
            model_name='pokemonmove',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.PokemonMoveCategory'),
        ),
        migrations.AddField(
            model_name='pokemonmove',
            name='description',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Description'),
        ),
        migrations.AddField(
            model_name='pokemonmove',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name'),
        ),
        migrations.AddField(
            model_name='pokemonmove',
            name='secondary_effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.SecondaryEffect'),
        ),
        migrations.AddField(
            model_name='pokemonmove',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.PokemonType'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='can_learn_moves',
            field=models.ManyToManyField(blank=True, to='pokedex.PokemonMove'),
        ),
    ]
