# Generated by Django 2.0.6 on 2018-07-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_auto_20180701_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='pokedex.PokemonAbility'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hidden_ability',
            field=models.ManyToManyField(blank=True, related_name='hidden_ability', to='pokedex.PokemonAbility'),
        ),
    ]
