# Generated by Django 2.0.6 on 2018-07-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0009_auto_20180701_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveAffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Description')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name')),
            ],
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.PokemonMoveCategory'),
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.Description'),
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='secondary_effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.SecondaryEffect'),
        ),
        migrations.AddField(
            model_name='pokemonmove',
            name='affect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.MoveAffect'),
        ),
    ]
