# Generated by Django 2.0.6 on 2018-07-01 14:47

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('pokedex', '0010_auto_20180701_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoveAffect',
            new_name='MoveAffectSpec',
        ),
        migrations.RenameModel(
            old_name='PokemonAbility',
            new_name='PokemonAbilitySpec',
        ),
        migrations.RenameModel(
            old_name='PokemonMove',
            new_name='PokemonMoveSpec',
        ),
        migrations.RenameModel(
            old_name='Pokemon',
            new_name='PokemonSpec',
        ),
        migrations.RenameModel(
            old_name='SecondaryEffect',
            new_name='SecondaryEffectSpec',
        ),
    ]
