# Generated by Django 2.0.6 on 2018-07-01 14:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('pokedex', '0011_auto_20180701_2347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoveAffectSpec',
            new_name='MoveAffect',
        ),
        migrations.RenameModel(
            old_name='PokemonSpec',
            new_name='Pokemon',
        ),
        migrations.RenameModel(
            old_name='PokemonAbilitySpec',
            new_name='PokemonAbility',
        ),
        migrations.RenameModel(
            old_name='PokemonMoveSpec',
            new_name='PokemonMove',
        ),
        migrations.RenameModel(
            old_name='SecondaryEffectSpec',
            new_name='SecondaryEffect',
        ),
    ]
