# Generated by Django 2.0.6 on 2018-07-01 15:03

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('pokedex', '0012_auto_20180701_2355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon',
            new_name='PokemonSpec',
        ),
    ]
