# Generated by Django 2.0.6 on 2018-07-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0014_remove_pokemonspec_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decreased_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokedex.Name')),
                ('increased_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokedex.Name')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Name')),
            ],
        ),
        migrations.RenameField(
            model_name='pokemonspec',
            old_name='abilities',
            new_name='can_have_abilities',
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='affect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.MoveAffect'),
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.PokemonMoveCategory'),
        ),
        migrations.AlterField(
            model_name='pokemonmove',
            name='secondary_effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.SecondaryEffect'),
        ),
    ]
