# Generated by Django 2.0.6 on 2018-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0016_auto_20180706_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemontype',
            name='ineffective_typs',
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='ineffective_types',
            field=models.ManyToManyField(blank=True, related_name='_pokemontype_ineffective_types_+', to='pokedex.PokemonType'),
        ),
    ]
