# Generated by Django 2.0.6 on 2018-07-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_maker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplepokemon',
            old_name='sp_attack_EV',
            new_name='special_attack_EV',
        ),
        migrations.RenameField(
            model_name='samplepokemon',
            old_name='sp_attack_IV',
            new_name='special_attack_IV',
        ),
        migrations.RenameField(
            model_name='samplepokemon',
            old_name='sp_defense_EV',
            new_name='special_defense_EV',
        ),
        migrations.RenameField(
            model_name='samplepokemon',
            old_name='sp_defense_IV',
            new_name='special_defense_IV',
        ),
    ]
